file = open('D:/test/frq.txt', 'w')
Str = 'MNAPERQPQPDGGDAPGHEPGGSPQDELDFSILFDYEYLNPNEE\
EPNAHKVASPPSGPAYPDDVLDYGLKPYSPLASLSGEPPGRFGEPDRVGPQ\
KFLSAAKPAGASGLSPRIEITPSHELIQAVGPLRMRDAGLLVEQPPLAGVA\
ASPRFTLPVPGFEGYREPLCLSPASSGSSASFISDTFSPYTSPCVSPNNGG\
PDDLCPQFQNIPAHYSPRTSPIMSPRTSLAEDSCLGRHSPVPRPASRSSSP\
GAKRRHSCAEALVALPPGASPQRSRSPSPQPSSHVAPQDHGSPAGYPPVAG\
SAVIMDALNSLATDSPCGIPPKMWKTSP'
resoult = {}  # 定义一个空字典
for i in Str:  # 遍历输入的字符串，以键值对的方式存储在字典中
    resoult[i] = Str.count(i)  
for key in resoult:# 遍历字典，格式化输出结果
   print(f'{key} {resoult[key]}',end='\n')
file.close()  # 关闭文件
